// Date: 4/10/2014 6:11:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.tinkerlad.dimension.tileEntities.TESR;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class DimensionalBedModel extends ModelBase
{
  //fields
    ModelRenderer BED;
    ModelRenderer LegBL;
    ModelRenderer LegBR;
    ModelRenderer LegTL;
    ModelRenderer LegTR;
  
	public DimensionalBedModel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      BED = new ModelRenderer(this, 0, 0);
      BED.addBox(-16F, 0F, -24F, 32, 8, 48);
      BED.setRotationPoint(8F, 8F, 16F);
      BED.setTextureSize(128, 128);
      BED.mirror = true;
      setRotation(BED, 0F, 0F, 0F);
      LegBL = new ModelRenderer(this, 0, 16);
      LegBL.addBox(0F, 16F, 0F, 4, 8, 4);
      LegBL.setRotationPoint(-8F, 0F, -8F);
      LegBL.setTextureSize(128, 128);
      LegBL.mirror = true;
      setRotation(LegBL, 0F, 0F, 0F);
      LegBR = new ModelRenderer(this, 16, 16);
      LegBR.addBox(0F, 0F, 0F, 4, 8, 4);
      LegBR.setRotationPoint(20F, 16F, -8F);
      LegBR.setTextureSize(128, 128);
      LegBR.mirror = true;
      setRotation(LegBR, 0F, 0F, 0F);
      LegTL = new ModelRenderer(this, 0, 0);
      LegTL.addBox(0F, 0F, 0F, 4, 8, 4);
      LegTL.setRotationPoint(-8F, 16F, 36F);
      LegTL.setTextureSize(128, 128);
      LegTL.mirror = true;
      setRotation(LegTL, 0F, 0F, 0F);
      LegTR = new ModelRenderer(this, 16, 0);
      LegTR.addBox(0F, 0F, 0F, 4, 8, 4);
      LegTR.setRotationPoint(20F, 16F, 36F);
      LegTR.setTextureSize(128, 128);
      LegTR.mirror = true;
      setRotation(LegTR, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BED.render(f5);
    LegBL.render(f5);
    LegBR.render(f5);
    LegTL.render(f5);
    LegTR.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
